CREATE TABLE [dbo].[ATRIBUT] (
    [SIF_TABLICE] SMALLINT     NOT NULL,
    [SIF_KOLONE]  SMALLINT     NOT NULL,
    [NAZ_TABLICE] VARCHAR (50) NOT NULL,
    [NAZ_KOLONE]  VARCHAR (50) NOT NULL,
    [OZN_AKT]     SMALLINT     NOT NULL,
    [TSTAMP]      DATETIME     NOT NULL,
    CONSTRAINT [PK_ATRIBUT] PRIMARY KEY CLUSTERED ([SIF_TABLICE] ASC, [SIF_KOLONE] ASC)
);

