CREATE TABLE [dbo].[KATEGORIJA_POPUSTA] (
    [ID_KATEGORIJE]  INT           IDENTITY (1, 1) NOT NULL,
    [NAZ_KATEGORIJE] VARCHAR (200) NOT NULL,
    [OZN_AKT]        SMALLINT      NOT NULL,
    CONSTRAINT [PK_KATEGORIJA_POPUSTA] PRIMARY KEY CLUSTERED ([ID_KATEGORIJE] ASC)
);

