CREATE TABLE [dbo].[MENU_GRUPA] (
    [ID_GRUPE]   SMALLINT     IDENTITY (1, 1) NOT NULL,
    [NAZ_GRUPE]  VARCHAR (50) NOT NULL,
    [RBR_PRIKAZ] SMALLINT     NOT NULL,
    [OZN_AKT]    SMALLINT     NOT NULL,
    [TSTAMP]     DATETIME     NOT NULL,
    CONSTRAINT [PK_MENU_GRUPA] PRIMARY KEY CLUSTERED ([ID_GRUPE] ASC)
);

