CREATE TABLE [dbo].[MENU_STAVKA] (
    [ID_STAVKE]  SMALLINT     NOT NULL,
    [ID_GRUPE]   SMALLINT     NOT NULL,
    [NAZ_STAVKE] VARCHAR (50) NOT NULL,
    [RBR_PRIKAZ] SMALLINT     NOT NULL,
    [OZN_AKT]    SMALLINT     NOT NULL,
    [TSTAMP]     DATETIME     NOT NULL,
    CONSTRAINT [PK_MENU_STAVKA] PRIMARY KEY CLUSTERED ([ID_STAVKE] ASC),
    CONSTRAINT [FK_MENU_STAVKA_MENU_GRUPA] FOREIGN KEY ([ID_GRUPE]) REFERENCES [dbo].[MENU_GRUPA] ([ID_GRUPE])
);

