CREATE TABLE [dbo].[POPUST] (
    [ID_POPUSTA]    INT           IDENTITY (1, 1) NOT NULL,
    [ID_VLASNIKA]   INT           NOT NULL,
    [ID_KATEGORIJE] INT           NOT NULL,
    [NAZIV_POPUSTA] VARCHAR (200) NOT NULL,
    [IZNOS]         NCHAR (10)    NOT NULL,
    [DAT_OD]        ROWVERSION    NOT NULL,
    [DAT_DO]        NCHAR (10)    NOT NULL,
    [OZN_AKT]       SMALLINT      NOT NULL,
    [TIMESTAMP]     DATETIME      NOT NULL,
    CONSTRAINT [PK_POPUST] PRIMARY KEY CLUSTERED ([ID_POPUSTA] ASC),
    CONSTRAINT [FK_POPUST_KATEGORIJA_POPUSTA] FOREIGN KEY ([ID_KATEGORIJE]) REFERENCES [dbo].[KATEGORIJA_POPUSTA] ([ID_KATEGORIJE]),
    CONSTRAINT [FK_POPUST_VLASNIK] FOREIGN KEY ([ID_VLASNIKA]) REFERENCES [dbo].[VLASNIK] ([ID_VLASNIKA])
);

