CREATE TABLE [dbo].[POSLOVNICA] (
    [ID_POSLOVNICE]  INT           IDENTITY (1, 1) NOT NULL,
    [ID_VLASNIKA]    INT           NOT NULL,
    [NAZ_POSLOVNICE] VARCHAR (200) NOT NULL,
    [TSTAMP]         DATETIME      NOT NULL,
    CONSTRAINT [PK_POSLOVNICA] PRIMARY KEY CLUSTERED ([ID_POSLOVNICE] ASC),
    CONSTRAINT [FK_POSLOVNICA_VLASNIK] FOREIGN KEY ([ID_VLASNIKA]) REFERENCES [dbo].[VLASNIK] ([ID_VLASNIKA])
);


GO
CREATE NONCLUSTERED INDEX [IX_POSLOVNICA]
    ON [dbo].[POSLOVNICA]([ID_POSLOVNICE] ASC);

