CREATE TABLE [dbo].[TRANSAKCIJA] (
    [ID_TRANS]          INT         NOT NULL,
    [ID_APP_USER]       INT         NOT NULL,
    [ID_VLASNIKA]       INT         NOT NULL,
    [TIMESTAMP]         DATETIME    NOT NULL,
    [STS]               VARCHAR (2) NOT NULL,
    [TSTAMP_KREIRANJA]  DATETIME    NOT NULL,
    [TSTAMP_SLANJA]     DATETIME    NULL,
    [TSTAMP_POTVRDE]    DATETIME    NULL,
    [TSTAMP_PONISTENJA] DATETIME    NULL,
    CONSTRAINT [PK_TRANSAKCIJA] PRIMARY KEY CLUSTERED ([ID_TRANS] ASC),
    CONSTRAINT [FK_TRANSAKCIJA_APP_KORISNIK] FOREIGN KEY ([ID_APP_USER]) REFERENCES [dbo].[APP_KORISNIK] ([ID_APP_USER]),
    CONSTRAINT [FK_TRANSAKCIJA_VLASNIK] FOREIGN KEY ([ID_VLASNIKA]) REFERENCES [dbo].[VLASNIK] ([ID_VLASNIKA])
);

