CREATE TABLE [dbo].[ULOGA] (
    [ID_ULOGE]   SMALLINT      IDENTITY (1, 1) NOT NULL,
    [OPIS_ULOGE] VARCHAR (200) NOT NULL,
    [VR_ULOGE]   SMALLINT      NOT NULL,
    [OZN_AKT]    SMALLINT      NOT NULL,
    [TSTAMP]     DATETIME      NOT NULL,
    CONSTRAINT [PK_ULOGA] PRIMARY KEY CLUSTERED ([ID_ULOGE] ASC)
);

