CREATE TABLE [dbo].[ULOGA_STAVKA] (
    [ID_STAVKE] SMALLINT NOT NULL,
    [ID_ULOGE]  SMALLINT NOT NULL,
    [OZN_AKT]   SMALLINT NOT NULL,
    [TSTAMP]    DATETIME NOT NULL,
    CONSTRAINT [FK_ULOGA_STAVKA_ULOGA] FOREIGN KEY ([ID_ULOGE]) REFERENCES [dbo].[ULOGA] ([ID_ULOGE])
);

