CREATE TABLE [dbo].[VR_DOG] (
    [SIF_VR_DOG]   INT            NOT NULL,
    [UC]           VARCHAR (20)   NOT NULL,
    [OPIS_VR_DOG]  VARCHAR (200)  NOT NULL,
    [OPIS_ID1]     VARCHAR (200)  NULL,
    [OPIS_ID2]     VARCHAR (200)  NULL,
    [OPIS_ID3]     VARCHAR (200)  NULL,
    [OPIS_ID4]     VARCHAR (200)  NULL,
    [OZN_DET]      SMALLINT       NOT NULL,
    [OPIS_DETALJA] VARCHAR (1000) NULL,
    [OZN_AKT]      SMALLINT       NOT NULL,
    [TSTAMP]       ROWVERSION     NULL,
    CONSTRAINT [PK_VR_DOG] PRIMARY KEY CLUSTERED ([SIF_VR_DOG] ASC)
);

