CREATE TABLE [dbo].[VRJD_ATRIBUTA] (
    [SIF_TABLICE]      SMALLINT     NOT NULL,
    [SIF_KOLONE]       SMALLINT     NOT NULL,
    [VRIJEDNOST]       SMALLINT     NOT NULL,
    [OPIS_VRIJEDNOSTI] VARCHAR (50) NOT NULL,
    [OZN_AKT]          SMALLINT     NOT NULL,
    [TSTAMP]           DATETIME     NOT NULL,
    CONSTRAINT [PK_VRJD_ATRIBUTA_1] PRIMARY KEY CLUSTERED ([SIF_TABLICE] ASC, [SIF_KOLONE] ASC, [VRIJEDNOST] ASC),
    CONSTRAINT [FK_VRJD_ATRIBUTA_ATRIBUT] FOREIGN KEY ([SIF_TABLICE], [SIF_KOLONE]) REFERENCES [dbo].[ATRIBUT] ([SIF_TABLICE], [SIF_KOLONE])
);

