CREATE TABLE [shoppin1_ijadric].[KATEGORIJA_PROIZVODA] (
    [ID_KATEGORIJE_PROIZVODA] INT          NOT NULL,
    [NAZ_KATEGORIJE]          VARCHAR (50) NULL,
    PRIMARY KEY CLUSTERED ([ID_KATEGORIJE_PROIZVODA] ASC)
);

